version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\deploytmp
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
  AfterInstall:
    - location: \after-install.bat
      timeout: 900
