version: 0.0
os: windows
files:
  - source: .\JuniorTennis.Mvc\bin\Debug\netcoreapp3.1\publish\
    destination: c:\inetpub\deploytmp
  - source: .\appspec.yml
    destination: c:\inetpub\deploytmp
  - source: .\before-install.bat
    destination: c:\inetpub\deploytmp
  - source: .\after-install.bat
    destination: c:\inetpub\deploytmp
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
  AfterInstall:
    - location: \after-install.bat
      timeout: 900
