version: 0.0
os: windows
files:
  - source: \JuniorTennis.Mvc\bin\Debug\netcoreapp3.1\publish\
    destination: c:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
  AfterInstall:
    - location: \after-install.bat
      timeout: 900
