version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish
      - ls -l ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish
artifacts:
  files:
    - ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/*
    - ./appspec.yml
    - ./before-install.bat
    - ./after-install.bat