version: 0.2

phases:
  build:
    commands:
      - dotnet publish ./JuniorTennis.sln
      - cd ./React/public
      - npm install
      - npm run build
artifacts:
  secondary-artifacts:
    EC2Artifact:
      files:
        - ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish/**/*
        - ./appspec.yml
        - ./before-install.bat
        - ./after-install.bat
    S3Artifact:
      base-directory: ./React/build
      files:
        - '**/*'
