version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish
      - cp appspec.yml ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish/
      - cp before-install.bat ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish/
      - cp after-install.bat ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish/
artifacts:
  files:
    - ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish/*
    